CREATE TABLE IF NOT EXISTS MODEL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAMA VARCHAR(255),
    ALAMAT VARCHAR(255),
    KOTA VARCHAR(255),
    PROV VARCHAR(255),
    TGL_REG DATE,
    STS VARCHAR(255)
);